### ISSUE TITLE
ReadDiversionHistoricalTSMonthlyFromHydroBase (FillUsingCIU=True) not skipping missing WDIDs

### ISSUE THREAD

**Issue by macphersonbr** [OpenCDSS/cdss-app-statedmi-main#106]
ReadDiversionHistoricalTSMonthlyFromHydroBase(ID="*",IncludeCollections=False,UseDiversionComments=True,FillUsingCIU="True",FillUsingCIUFlag=Auto) is not skipping missing WDIDs. The expected functionality is that it skips missing WDIDs according to the documentation. In the attached command file, it bombs when it gets to 7102999 because it is not in HydroBase. The command skips that WDID when FillUsingCIU=False. It is OK that that WDID is missing in HydroBase because it gets filled with an .stm later. See line 26 of command file.

The resultant .ddh file does not write out any of the WDIDs > 7102999 in each year. See comparison of .ddh files with FillUsingCIU=True and FillUsingCIU=False.

Log File lines 1608-1627:
Status[2](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): Reading diversion time series for "7102999"
Warning[3](HydroBaseDMI.readTimeSeries): Unable to find structure "7102999"
Status[2](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): Unable to read diversion time series data from HydroBase for 7102999
Status[2](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): No HydroBase diversion time series data found for requested ID "7102999".  Adding an empty time series.
Status[2](HydroBase_Util.fillDiversionUsingComments): No diversion comments for 7102999.DWR.DiversionHist.Month.  Not filling data.
Warning[3](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): Exception stack trace follows (see log file)...
Warning[3](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): null
java.lang.NullPointerException
	at DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.fillUsingCIUFlag(ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.java:406)
	at DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand(ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.java:1111)
	at DWR.DMI.StateDMI.StateDMI_Processor.processCommands(StateDMI_Processor.java:4771)
	at DWR.DMI.StateDMI.StateDMI_Processor.runCommands(StateDMI_Processor.java:6490)
	at DWR.DMI.StateDMI.StateDMI_Processor.processRequest_RunCommands(StateDMI_Processor.java:5503)
	at DWR.DMI.StateDMI.StateDMI_Processor.processRequest(StateDMI_Processor.java:5175)
	at DWR.DMI.StateDMI.StateDMI_Processor_ThreadRunner.run(StateDMI_Processor_ThreadRunner.java:87)
	at java.lang.Thread.run(Unknown Source)
Warning[3](DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): ... end of exception stack trace.
Warning[2]<26,1>(DWR.DMI.StateDMI.ReadDiversionHistoricalTSMonthlyFromHydroBase_Command.runCommand): Unexpected error reading diversion historical time series (java.lang.NullPointerException).
Warning[2]<26,1>(StateDMI.processCommands): Error processing command - unable to complete command (RTi.Util.IO.CommandException: Unexpected error reading diversion historical time series (java.lang.NullPointerException).).
Status[1]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

[sj2020.ddh_CIUFalse.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6976848/sj2020.ddh_CIUFalse.txt)
[sj2020.ddh_CIUTrue.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6976852/sj2020.ddh_CIUTrue.txt)
[ddh.commands_2020.StateDMI.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6976859/ddh.commands_2020.StateDMI.txt)
[StateDMI_bdm.log](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6976803/StateDMI_bdm.log)

**Comment by macphersonbr** [comment]
Supporting files for command line below:

[sj2020_dds.dds.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977246/sj2020_dds.dds.txt)
[sj_agg_2020.csv](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977251/sj_agg_2020.csv)
[sj_divsys_StateMod_2020.csv](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977252/sj_divsys_StateMod_2020.csv)
[fill2020.pat.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977253/fill2020.pat.txt)
[Dolores_Project_2020.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977260/Dolores_Project_2020.stm.txt)
[Historic_Florida.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977264/Historic_Florida.stm.txt)
[Task11.2_2020.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977272/Task11.2_2020.stm.txt)
[SanMiguel_2020.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977273/SanMiguel_2020.stm.txt)
[Spring_Creek_Dr_Morrison.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6977283/Spring_Creek_Dr_Morrison.stm.txt)
